# Generated by Django 3.1.1 on 2020-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200916_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='recurso',
            field=models.CharField(max_length=100, verbose_name='Recurso'),
        ),
    ]
